config/routes.rb
Rails.application.routes.draw do

  	devise_for :users
	root 'main#index' #redirecciona a la pagina principal
    get '/faq', to:'preguntasfrecuentes#faq' #ruta para poder acceder a las faq

    resources :residences, :auctions, :users, :searches, :hotsales, :reservations, :availabilitys, :settings #para poder acceder a las residencias, subastas, usuarios y busquedas
    resources :users do
  		member do
    		get 'be_premium'
            get 'apply_premium'
            get 'enable_premium'
            get 'disable_premium'
 		end
	end
    #ADMINISTRADORES
    get '/admins', to:'users#indexAdmins'
    get '/admins/new', to:'users#newAdmin'
    post '/admins', to:'users#createAdmin'
    get '/admins/:id/destroy', to:'users#destroyAdmin'
    delete '/admins/:id/destroy', to:'users#destroyAdmin', as: 'admin_destroy'

    #USERS
    get '/clients/:id/delete', to:'users#deleteClient', as: 'client_delete'
    get '/clients/deleted', to:'users#deletedClient', as: 'client_deleted'
    get '/clients/:id/destroy', to:'users#destroyClient'
    delete '/clients/:id/destroy', to:'users#destroyClient', as: 'client_destroy'

    #RESERVAS
    get '/reservations/:id/pay_reservation', to: 'reservations#pay_reservation', as: 'pay_reservation' 
    post '/reservations/:id/pay', to: 'reservations#pay', as: 'pay'

    #
    get '/enterBid', to:'auctions#enterBid'
    get '/contact', to:'contacto#contact'
    post '/contact_success', to:'contacto#contact_success'
end

app/models/auction.rb
class Auction < ApplicationRecord
	belongs_to :residence
	has_and_belongs_to_many :users
	belongs_to :user
	belongs_to :availability

 	#FUNCTION SQL PARA ENCONTRAR UNA FECHA ENTRE DOS FECHAS
	#scope :open, -> { where("? BETWEEN dateStart AND dateEnd", Date.today)}
	#scope :closed, -> { where("? NOT BETWEEN dateStart AND dateEnd", Date.today)}

	#FUNCTION POSTGRESQL PARA ENCONTRAR UNA FECHA ENTRE DOS FECHAS
 	scope :open, -> {where(':date BETWEEN Auctions."dateStart" AND Auctions."dateEnd"', date: Date.today)}
 	scope :closed, -> {where(':date NOT BETWEEN Auctions."dateStart" AND Auctions."dateEnd"', date: Date.today)}
	scope :pending, -> {where(':date < Auctions."dateStart"', date: Date.today)}
 	scope :finished, -> {where(':date > Auctions."dateEnd"', date: Date.today)}

	def isActive()
		if Date.today > self.dateStart && Date.today < self.dateEnd
			return true
		else
			return false
		end
	end

end

app/models/auctions_user.rb
class AuctionsUser < ApplicationRecord
  belongs_to :user
  belongs_to :auction
end

app/models/availability.rb
class Availability < ApplicationRecord
  belongs_to :residence
end

app/models/hotsale.rb
class Hotsale < ApplicationRecord
  belongs_to :residence
  belongs_to :availability
  
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :residence
  belongs_to :user
end

app/models/residence.rb
class Residence < ApplicationRecord
	default_scope -> { order :name }
	has_many :auctions
	has_many :reservations
	has_many :availabilities, dependent: :destroy
	validates :image_url, allow_blank: true, format: { with: %r{.(gif|jpg|png)\Z}i, message: 'must be a URL for GIF, JPG or PNG image.' }
	
	scope :open, -> {where(available: 1)}
  	scope :closed, -> {where(available: 0)}

	def self.search(search)
		if search
			where(["name LIKE ? OR dir LIKE ? OR country LIKE ? OR province LIKE ? OR locality LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%"])
		else
			Residence.all
		end
	end
end

app/models/search.rb
class Search < ApplicationRecord

	def search_residences
		residences = Residence.all

		residences = residences.where(["name LIKE ?","%#{keywords}%"]) if keywords.present?
		residences = residences.where(["dir LIKE ?","%#{dir}%"]) if dir.present?
		#residences = residences.where(["desc LIKE ?","%#{desc}%"]) if desc.present?
		residences = residences.where(["country LIKE ?","%#{country}%"]) if country.present?
		residences = residences.where(["province LIKE ?","%#{province}%"]) if province.present?
		residences = residences.where(["locality LIKE ?","%#{locality}%"]) if locality.present?

		return residences
	end
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_and_belongs_to_many :auctions
  has_many :reservations

  enum isPremium: { si: 0, solicitado: 1, no: 2 }

  scope :admins, -> {where(isAdmin: 1)}
  scope :clients, -> {where(isAdmin: 0)}

  validate :age_is_invalid, :expiry_date_is_invalid, :credit_card_number_is_invalid

  #Deje el self.isAdmin porque current_user solo funciona cuando lo usas desde un controlador o una vista. NO funciona en modelos, para eso hay que usar el self.
  def age_is_invalid
    if self.isAdmin == false
      today = Date.today
      if today - self.birthday < 18
        errors.add(:birthday, "Necesita ser mayor de edad para registrarse")
      end
    end
  end

  def expiry_date_is_invalid
    if self.isAdmin == false
  	 if self.card_expiry_date.present? && card_expiry_date <= Date.today
      	 errors.add(:card_expiry_date, "La fecha de vencimiento de la tarjeta ha caducado o esta punto de vencer")
      end
    end
  end

  def credit_card_number_is_invalid
    if self.isAdmin == false
     if self.credit_card_number.present? && self.credit_card_number.to_s.length < 14
         errors.add(:credit_card_number, "El numero de la tarjeta debe ser de al menos 14 digitos")
      end
    end
  end

  def cvv_is_invalid
    if self.isAdmin == false
      if self.cvv? && self.cvv.to_s.length < 3
        errors.add(:cvv, "El numero de la clave de seguridad de la tarjeta debe ser de al menos 3 digitos")
      end
    end
  end

end

app/models/utils.rb
class Utils
  require 'net/http'
  require 'uri'

  def self.image_exists?(url_param)
    url = URI.parse(url_param)
    http = Net::HTTP.start(url.host, url.port)
    binding.pry
    http.head(url.request_uri)['Content-Type'].start_with? 'image'
  end

end

app/controllers/contacto_controller.rb
class ContactoController < ApplicationController
  def contact
  end
  def contact_success
  end
end

app/helpers/auction_helper.rb
module AuctionHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/helpers/contacto_helper.rb
module ContactoHelper
end

app/helpers/hotsales_helper.rb
module HotsalesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/residences_helper.rb
module ResidencesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacto/contact.html.erb
<div class="hsh-window">
  <%= form_tag contact_success_path %>
    <div class="form-row">
      <label for="exampleInputEmail1">Ingrese nombre y apellido</label> 
    </div>
    <div class="form-row">
      <div class="col">
        <input type="text" class="form-control" placeholder="Nombre" required>
      </div>
      <div class="col">
        <input type="text" class="form-control" placeholder="Apellido" required>
      </div>
  </div>
    <br>
    <div class="form-group">
      <label for="exampleInputEmail1">Email</label>
      <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"placeholder="Ingrese su email" required>
    </div>
    <br>
    <div class="form-group">
      <label for="formGroupExampleInput2">Asunto</label>
      <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Asunto" required>
    </div>
    <div class="form-row">
      <label for="exampleInputEmail1">Consulta</label> 
    </div>
    <div class="input-group">
      <textarea class="form-control" aria-label="With textarea" required></textarea>
    </div>
    <br>
    <div>
      <%= link_to "Volver", :back, class: 'btn btn-secondary' %>
      <%= button_to 'Enviar', { action: "contact_success" }, class: 'btn btn-primary'  %>
    </div>
  </form>
</div>

app/views/contacto/contact_success.html.erb
<div class="hsh-window">
	<div class="container" style="border: 1px solid grey; border-radius: 5px; padding: 60px">

		<div class="row alert alert-primary noselect" role="alert"  style="margin-bottom: 200px">
	 		Tu consulta ha sido enviada exitosamente. Nos pondremos en contacto con usted a la brevedad.
		</div>

		<div class="row"">
		<%= link_to "Volver a pagina principal", root_path, class: 'btn btn-primary'%>
		</div>
		
	</div>
</div>