config/routes.rb
Rails.application.routes.draw do

  	devise_for :users
	root 'main#index' #redirecciona a la pagina principal
    get '/faq', to:'preguntasfrecuentes#faq' #ruta para poder acceder a las faq

    resources :residences, :auctions, :users, :searches, :hotsales, :reservations, :availabilitys, :settings #para poder acceder a las residencias, subastas, usuarios y busquedas
    resources :users do
  		member do
    		get 'be_premium'
            get 'apply_premium'
            get 'enable_premium'
            get 'disable_premium'
 		end
	end
    #ADMINISTRADORES
    get '/admins', to:'users#indexAdmins'
    get '/admins/new', to:'users#newAdmin'
    post '/admins', to:'users#createAdmin'
    get '/admins/:id/destroy', to:'users#destroyAdmin'
    delete '/admins/:id/destroy', to:'users#destroyAdmin', as: 'admin_destroy'

    #USERS
    get '/clients/:id/delete', to:'users#deleteClient', as: 'client_delete'
    get '/clients/deleted', to:'users#deletedClient', as: 'client_deleted'
    get '/clients/:id/destroy', to:'users#destroyClient'
    delete '/clients/:id/destroy', to:'users#destroyClient', as: 'client_destroy'

    #RESERVAS
    get '/reservations/:id/pay_reservation', to: 'reservations#pay_reservation', as: 'pay_reservation' 
    post '/reservations/:id/pay', to: 'reservations#pay', as: 'pay'

    #
    get '/enterBid', to:'auctions#enterBid'
    get '/contact', to:'contacto#contact'
    post '/contact_success', to:'contacto#contact_success'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_and_belongs_to_many :auctions
  has_many :reservations

  enum isPremium: { si: 0, solicitado: 1, no: 2 }

  scope :admins, -> {where(isAdmin: 1)}
  scope :clients, -> {where(isAdmin: 0)}

  validate :age_is_invalid, :expiry_date_is_invalid, :credit_card_number_is_invalid

  #Deje el self.isAdmin porque current_user solo funciona cuando lo usas desde un controlador o una vista. NO funciona en modelos, para eso hay que usar el self.
  def age_is_invalid
    if self.isAdmin == false
      today = Date.today
      if today - self.birthday < 18
        errors.add(:birthday, "Necesita ser mayor de edad para registrarse")
      end
    end
  end

  def expiry_date_is_invalid
    if self.isAdmin == false
  	 if self.card_expiry_date.present? && card_expiry_date <= Date.today
      	 errors.add(:card_expiry_date, "La fecha de vencimiento de la tarjeta ha caducado o esta punto de vencer")
      end
    end
  end

  def credit_card_number_is_invalid
    if self.isAdmin == false
     if self.credit_card_number.present? && self.credit_card_number.to_s.length < 14
         errors.add(:credit_card_number, "El numero de la tarjeta debe ser de al menos 14 digitos")
      end
    end
  end

  def cvv_is_invalid
    if self.isAdmin == false
      if self.cvv? && self.cvv.to_s.length < 3
        errors.add(:cvv, "El numero de la clave de seguridad de la tarjeta debe ser de al menos 3 digitos")
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #@user = User.find params[:user_id]
  #@auction = @user.auctions.find params[:id]
  #@auction << current_user
  protect_from_forgery #para que ande createAdmin

  def index
    @user = User.all
  end

  def indexAdmins
    @admin = User.admins
  end

  def new
  	@user = User.new
  end

  def newAdmin
    @admin = User.new
  end

  def create
    @user = User.new( params.require(:user).permit(:userName, :email, :password, :isAdmin, :isPremium, :credits, :name, :surname, :birthday, :credit_card_number, :cvv, :card_expiry_date) )
    if @user.save
        redirect_to users_path, notice: "Se añadio un usuario exitosamente."
    else
      render :new
    end
  end

  def createAdmin
    @admin = User.new( params.require(:user).permit(:userName, :email, :password, :credits, :isAdmin) )
    if @admin.save
      redirect_to admins_path, notice: "Se añadio un admin exitosamente."
    else
      @error = "Contrasena muy debil"
      render :newAdmin
    end
  end

  def show
  	@user = User.find(params[:id])
    @cc_number = mask @user.credit_card_number.to_s
    @auctions = @user.auctions
  end

  def destroy
    @user = User.destroy(params[:id])
    redirect_to root_path
  end

  def deleteClient
    @client = User.find(params[:id])
    @clientReservations = @client.reservations
    @clientAuctions = @client.auctions
  end
  def deletedClient
    @deletedWasPremium = :deletedWasPremium
  end

  def destroyClient
    @client = User.find(params[:id])
    @deletedWasPremium = @client.isPremium
    @client = User.destroy(params[:id])
    redirect_to client_deleted_path
  end

  def destroyAdmin
    @admin = User.destroy(params[:id])
    redirect_to admins_path
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if !@user.isAdmin?
      @user.update(user_params)
    else
      @user.update(admin_params)
    end
    redirect_to user_path
  end
  #Usado para mandar parametros del usuario. Lo uso en la modificacion del usuario para actualizar los datos.
  #Se puede usar para otros metdos, como por ej. create.
  def user_params
    params.require(:user).permit(:userName, :email, :password, :isAdmin, :isPremium, :credits, :name, :surname, :birthday, :credit_card_number, :cvv, :card_expiry_date)
  end
  def admin_params
    params.require(:user).permit(:userName, :email, :password, :isAdmin, :credits)
  end

  def be_premium
    @user = User.find(params[:id])
  end

  def apply_premium
    @user = User.find(params[:id])
    @user.isPremium = "solicitado"
    @user.save
    redirect_to current_user, notice: 'Su solicitud ha sido enviada con exito.'
  end

  def enable_premium
    @user = User.find(params[:id])
    @user.isPremium = "si"
    @user.save
    redirect_to users_path
  end

  def disable_premium
    @user = User.find(params[:id])
    @user.isPremium = "no"
    @user.save
    redirect_to users_path
  end

  def last_digits(number)    
    number.to_s.length <= 4 ? number : number.to_s.slice(-4..-1) 
  end

  def mask(number)
    "XXXX-XXXX-XXXX-#{last_digits(number)}"
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_formAdmin.html.erb
<div class="container">

  <div class="row br30">
    <h1> Alta de Administrador </h1>
  </div>

  <%= form_for @admin, :url => { :action => "createAdmin" }, :html => { :method => "createAdmin" } do |f|  %>
  <div class="row br30">
    <%= f.label :email, 'Email' %>
    <%= f.text_field :email, required: true, placeholder: "admin@mail.com", class: 'form-control'  %>
  </div>

  <div class="row br30">
    <%= f.label :password, 'Contrasena' %>
    <%= f.password_field :password, required: true, class: 'form-control'  %>
  </div>

  <div class="row br30">
    <%= f.label :userName %>
    <%= f.text_field :userName, required: true, class: 'form-control' %>
  </div>

  <div class="row br30">
    <%= f.hidden_field :credits, value: 9 %>
    <%= f.hidden_field :isAdmin, value: true %>
  </div>

  <div class="row btn-gap">
    <p class="error"> <%= @error %></p>
    <%= link_to "Volver", :back, class: 'btn btn-secondary' %>
    <%= f.submit 'Guardar', class: 'btn btn-primary' %>
  <% end %>
  </div>

</div>

app/views/users/_formUser.html.erb
<div class="container">
  <%= form_for @user do |f| %>

  <div class="row">
    <%= f.label :name, 'Nombre de usuario' %>
    <%= f.text_field :userName, required: true, class: 'form-control' %>
  </div>
<% if current_user.userName == @user.userName %>
  <div class="row top10 br10">
    <%= link_to "Cambiar Datos de cuenta", edit_user_registration_path(@user) %>
  </div>
<% end %>

  <!-- DATOS PERSONALES -->
<% if !current_user.isAdmin%>
  <div class="row top30 br10">
    <h3>Datos personales</h3>
  </div>

  <div class="row">
    <div class="form-group col-md-6">
      <%= f.label :name, 'Nombre' %>
      <%= f.text_field :name, required: true, class: 'form-control' %>
    </div>

    <div class="form-group col-md-6">
      <%= f.label :surname, 'Apellido' %>
      <%= f.text_field :surname, required: true, class: 'form-control' %>
    </div>
  </div>

  <div class="row br10 col-md-6">
    <%= f.label :birthday, 'Fecha de nacimiento' %>
    <%= f.text_field :birthday, start_year: 1900, end_year: Date.today.year, :use_month_names => ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre','Diciembre'], :order => [:day, :month, :year], required: true, type: 'date', class: 'form-control' %>
  </div>

  <div class="row">
    <div class="form-group col-md-6">
      <%= f.label :credit_card_number, 'Numero de tarjeta de credito' %>
      <%= f.text_field :credit_card_number, maxlength: 16, required: true, class: 'form-control' %>
    </div>

    <div class="form-group col-md-2">
      <%= f.label :card_expiry_date, 'Fecha de vencimiento de tarjeta' %>
      <%= f.date_select :card_expiry_date, start_year: Date.today.year, use_two_digit_numbers: true, discard_day: true, :order => [:month, :year], required: true,  class: 'form-control' %>
    </div>

    <div class="form-group col-md-2">
      <%= f.label :cvv, 'Codigo de seguridad' %>
      <%= f.text_field :cvv, maxlength: 4, required: true, class: 'form-control' %>
    </div>
  </div>
<% end %>

  <% if current_user.isAdmin%> <!--Solo muestro a los administradores -->
    <div class="row">
      <%= f.label :credits, 'Creditos' %>
      <%= f.text_field :credits, required: true, class: 'form-control' %>
      <%= f.hidden_field :isAdmin, value: false %>
    </div>
  <% end %>

  <div class="row top30 btn-gap">
    <%if current_user.present? && current_user.isAdmin? %>
      <%= link_to "Volver", :back, class: 'btn btn-secondary' %>
    <%else%>
      <%= link_to "Volver", user_path, class: 'btn btn-secondary' %>
    <%end%>

    <%= f.submit 'Guardar', class: 'btn btn-primary' %>
  </div>

  <% end %>
</div>

app/views/users/be_premium.html.erb
<div class="hsh-window">
	<div class="container">
		<div class="row">
		<h1>Convertirse en un usuario premium</h1>
		<p>Estimado <%= @user.userName %>, esta a punto de pasar a ser parte de nuestros clientes con el mayor prestigio de nuestra empresa.</p>
		<p>Como parte de nuestros selectos usuarios premium usted tendra la capacidad en cualquiera de nuestras residencias al instante.</p>
		<p>Para pasar a formar parte de nuestros usuarios premium, debera depositar una suma de dinero en cualquiera de nuestras sucursales personalmente.</p>
		<p>Al presionar el boton confirmar, se dara inicio al tramite en el sistema. Se informara a nuestro personal y se pondra en contacto con usted a la brevedad para informarle cuanto debera depositar y las sucursales a las que puede concurrir para hacerlo.</p>
		</div>
		<div class="row">
				<%= link_to 'Confirmar', { :controller => 'users', :action => 'apply_premium' , :id=> @user.id }, class: 'btn btn-info'%>
				<%= link_to "Cancelar", root_path, class: 'btn btn-secondary'%>
		</div>
	</div>
</div>

app/views/users/deleteClient.html.erb
<div class="hsh-window">
	<div class="container">

		<% if current_user.isAdmin? %>
			<h1> Borrar Usuario - Admin </h1>
		  <p>Borrar este usuario - Ok?</p>
		<% end %>

		<% if current_user.present? && current_user.isPremium == 'no' && !current_user.isAdmin?  %>
			<h1> Borrar Mi Cuenta </h1>
		  <p>Estas seguro de querer borrar tu cuenta?</p>
		<% end %>

		<% if current_user.present? && current_user.isPremium == 'yes' && !current_user.isAdmin? %>
			<h1> Borrar Mi Cuenta Premium </h1>
			<p class="error">Usted debe pasar por alguna de las sucursales para firmar que desea borrar su usuario en el sistema.</p>
			<p>Estas seguro de querer borrar tu cuenta premium?</p>
		<% end %>

		<!-- BOTON BORRAR -->
		<% if @clientReservations.any? %>
		<p><%= link_to "Usted tiene reservas", client_destroy_path(@client),  class: 'btn btn-danger btn-sm disabled', data: { confirm: 'Realmente desea borrar su cuenta?'}%></p>
		<% else if @clientAuctions.any?%>
		<p><%= link_to "Usted esta ganando una subasta", client_destroy_path(@client),  class: 'btn btn-danger btn-sm disabled', data: { confirm: 'Realmente desea borrar su cuenta?'}%></p>
		<% else %>
		<p><%= link_to "Borrar", client_destroy_path(@client),  class: 'btn btn-danger btn-sm', data: { confirm: 'Realmente desea borrar su cuenta?'}%></p>
		<% end %>
		<% end %>

		<%= link_to "Volver", user_path, class: 'btn btn-secondary' %>

	</div>
</div>

app/views/users/deletedClient.html.erb
<div class="hsh-window">
	<div class="container">


		<% if user_signed_in? %>
			<h1> Usuario Borrado - Admin </h1>
			<p> La cuenta fue eliminada </p>
		<% end %>

		<% if @deletedWasPremium == 'no' && !user_signed_in?%>
			<h1> Cuenta Borrada </h1>
			<p> Su cuenta fue borrada </p>
		<% end %>

		<% if @deletedWasPremium == 'yes' && !user_signed_in? %>
			<h1> Cuenta Premium Borrada </h1>
			<p> Su cuenta fue borrada pero no totalmente </p>
			<p class="error">Usted debe pasar por alguna de las sucursales para firmar que desea borrar su usuario en el sistema.</p>
		<% end %>

		<% if true %>
			<h1> Cuenta Borrada </h1>
			<p> Su cuenta fue borrada </p>
		<% end %>

		<p> <%= link_to "Volver a pagina de inicio", root_path, class: 'btn btn-secondary' %> </p>

	</div>
</div>

app/views/users/destroy.html.erb
<div class="hsh-window">
	<div class="container">
			<h1> Usuario Borrado </h1>
			<p> La cuenta fue eliminada </p>
	</div>
</div>

app/views/users/edit.html.erb
<div class="hsh-window">
    <h1> Modificar el usuario "<%= @user.userName %>" </h1>
    <%= render 'formUser' %>
</div>

app/views/users/index.html.erb
<div class="hsh-window">
	<div class="container">

		<div class="row br30">
			<div class="col">
				<h1> Listado de Usuarios </h1>
			</div>
		</div>

		<div class="row br30">
			<table class="table">

				<tr>
					<th> Nombre de Usuario </th>
					<th> Email </th>
					<th> Creditos </th>
					<th> Categoria Premium </th>
				</tr>

				<% users = User.all %>
					<% users.each do |user| %>
					<% if not user.isAdmin%> <!--Solo muestro a los usuarios -->
						<tr>
							<% if current_user.id == 1 %>
							<td> <%= link_to user.userName, user %> </td>
							<% else %>
							<td> <%= user.userName %> </td>
							<% end %>
							<td> <%= user.email %> </td>
							<td> <%= user.credits %> </td>

							<%if user.isPremium == "si" %>
								<td>SI</td>
							<% else %>
							<%if user.isPremium == "solicitado" %>
								<td>SOLICITADO</td>
							<% else %>
								<td>NO</td>
							<% end %>
							<% end %>

							 <!-- Si soy admin vere este boton de hacer premium o no-->
							<% if current_user.isAdmin? %>
					      <% if user.isPremium == "solicitado" %> <!--Revisa si el usuario que esta mirando el administrador solicito ser premium-->
					        <td><%= link_to "Hacer Premium", enable_premium_user_path(user), data: {confirm: "Realmente desea hacer premium el usuario: #{user.userName} ?"}, class: 'btn btn-warning' %></td>
					      <% else %>
					      <% if user.isPremium == "si" %> <!--Si no entro en el anterior if, pregunta si ya es un usuario premium-->
					         <td><%= link_to "Baja Premium", disable_premium_user_path(user), data: {confirm: "Realmente desea bajar premium del usuario: #{user.userName} ?"},  class: 'btn btn-info' %></td>
					      <% else %>
					      	<td></td>
					      <% end %>
							  <% end %>
							<% end %>

				    	<!-- <td><%= link_to "Borrar", user, method: :delete,  class: 'btn btn-danger btn-sm', data: { confirm: "Realmente desea borrar el usuario: #{user.userName} ?"}%></td> -->
						</tr>
					<% end %>
				<% end %>

				<% if users.size == 0 %>
					<tr> <td colspan="3"> No hay usuarios </td> </tr>
				<% end %>
			</table>
		</div>

		<div class="row">
			<p> <%= link_to "Volver a pagina de inicio", root_path, class: 'btn btn-secondary' %> </p>
		</div>

	</div>
</div>

app/views/users/indexAdmins.html.erb
<div class="hsh-window">
	<div class="container">

		<div class="row br30">
			<div class="col">
				<h1 class="br30"> Listado de Administradores </h1>
				<%= link_to "Crear Administrador", admins_new_path ,class: 'btn btn-info' %>
			</div>
		</div>

		<div class="row br30">
			<table class="table">

				<tr>
					<th> Nombre de Usuario </th>
					<th> Email </th>
				</tr>

				<% admins = User.admins %> <!-- Uso un scope, mejor que un if -->
				<% admins.each do |admin| %>
						<tr>
							<td> <%= link_to admin.userName, user_path(admin.id) %> </td>
							<td> <%= admin.email %> </td>
							<td> <%= link_to "Editar", edit_user_path(admin.id), class: 'btn btn-info btn-sm'%> </td>
							<% if admin != current_user %>
								<% if admin.email == "root@mail.com" %>
								<td><%= link_to "Root", "/admins/#{admin.id}/destroy",  class: 'btn btn-danger btn-sm disabled', data: { confirm: 'Realmente desea borrar este administrador?'}%></td>
								<% else %>
								<td><%= link_to "Borrar", "/admins/#{admin.id}/destroy",  class: 'btn btn-danger btn-sm', data: { confirm: 'Realmente desea borrar este administrador?'}%></td>
								<% end %>
							<% else %>
								<td><%= link_to "Admin Actual", "/admins/#{admin.id}/destroy",  class: 'btn btn-danger btn-sm disabled', data: { confirm: 'Realmente desea borrar este administrador?'}%></td>
							<% end %>
						</tr>
					<% end %>

				<% if admins.size == 0 %>
					<tr> <td colspan="3"> No hay admins </td> </tr>
				<% end %>

			</table>
		</div>

		<div class="row">
			<p> <%= link_to "Volver a pagina de inicio", root_path, class: 'btn btn-secondary' %> </p>
		</div>

	</div>
</div>

app/views/users/newAdmin.html.erb
<div class="hsh-window">
  <%= render 'formAdmin' %>
</div>

app/views/users/show.html.erb
<div class="hsh-window">
  <div class="container">
    <h1>Perfil</h1>
      <!--PERFIL DE ADMIN-->
    <% if @user.isAdmin? %>
    <div class="profile row">
      <table class="profile-table">
        <tr>
          <td class="bold"> Nombre </td>
          <td class="profile-field"><%= @user.userName %></td>
        </tr>
        <tr>
          <td class="bold"> Email </td>
          <td class="profile-field"><%= @user.email %></td>
        </tr>
        <tr>
          <td class="bold"> Creado el </td>
          <td class="profile-field"><%= @user.created_at %></td>
        </tr>
        <tr>
          <td class="bold"> Editado el </td>
          <td class="profile-field"><%= @user.updated_at %></td>
        </tr>
        <tr>
          <td class="bold"> Administrador </td>
          <td class="profile-field"> <%= @user.isAdmin %> </td>
        </tr>
      </table>
    </div>
    <%else if !@user.isAdmin?%>
      <!--PERFIL DE USER-->
    <div class="row profile">
      <table class="profile-table">
        <tr>
          <td class="bold"> Nombre de usuario </td>
          <td class="profile-field"><%= @user.userName %></td>
        </tr>
        <tr>
          <td class="bold"> Email </td>
          <td class="profile-field"><%= @user.email %></td>
        </tr>
        <tr>
          <td class="bold"> Creditos </td>
          <td class="profile-field"><%= @user.credits %></td>
        </tr>
        <tr>
          <td class="bold"> Fecha de Nacimiento </td>
          <td class="profile-field"><%= @user.birthday.strftime("%d/%m/%Y") %></td>
        </tr>
        <tr>
          <td class="bold"> Premium </td>
          <td class="profile-field"><%= @user.isPremium %></td>
        </tr>
        <!--DATOS AGREGADOS-->
        <tr>
          <td class="bold">Nombre </td>
          <td class="profile-field"><%= @user.name %></td>
        </tr>
        <tr>
          <td class="bold"> Apellido </td>
          <td class="profile-field"><%= @user.surname %></td>
        </tr>
        <tr>
          <td class="bold"> Tarjeta de credito </td>
          <td class="profile-field"><%= @cc_number %></td>
        </tr>
      </table>
    </div>
    <% end %>
    <!--TABLA DE SUBASTAS-->
    <% if current_user.present? %>
    <div class="row">
      <h2>Subastas que vas ganando:</h2>
      <table class="table">
        <tr>
          <th></th>
          <th> Nombre de la Residencia </th>
          <th> Precio Actual </th>
          <th></th>
        </tr>
        <% auctions = Auction.all %>
          <% auctions.each do |auction| %>
            <% if auction.user_id == @user.id%>
              <tr>
                <td> <%= image_tag auction.residence.image_url, height: '100', width: '200' %></td>
                <td> <%= auction.residence.name %> </td>
                <td> <%= auction.maxbid %> </td>
                <td> <%= link_to "Ver", auction, class: 'btn btn-secondary' %> </td>
              </tr>
            <% end %>
          <% end %>
      </table>
    </div>
    <% end %>

    <!--TABLA DE RESERVAS-->
    <% if current_user.present? %>
    <div class="row br30" style="padding-top:70px">
      <h2>Tus reservas</h2>
      <table class="table">
        <tr>
          <th></th>
          <th> Nombre de la Residencia </th>

          <th> Semana </th>
        </tr>
        <% reservations = Reservation.all %>
          <% reservations.each do |reservation| %>
            <% if reservation.user_id == @user.id%>
              <tr>
                <td> <%= image_tag reservation.residence.image_url, height: '100', width: '200' %></td>
                <td> <%= reservation.residence.name %> </td>
                <td> Del <%= Date.commercial(reservation.year, reservation.week).strftime("%d/%m/%Y") %> hasta el <%= (Date.commercial(reservation.year, reservation.week) +6 ).strftime("%d/%m/%Y") %> </td>
                <td> <%= link_to "Ver detalles", reservation, class: 'btn btn-secondary' %> </td>
                <% if reservation.price > 0 && current_user.present? && current_user.id == reservation.user_id %>
                  <td> <%= link_to "Pagar", pay_reservation_path(:id=> reservation.id), class: 'btn btn-warning' %> </td>
                <% end %>
                <td> <%= link_to "Cancelar su reserva", reservation, method: :delete,  class: 'btn btn-danger', data: { confirm: "Realmente desea cancelar su reserva?"}%> </td>
              </tr>
            <% end %>
          <% end %>
      </table>
    </div>
    <% end %>

    <% end %>

      <!--MENU-->
    <div class="row btn-gap">

      <div class="col">
        <span><%= link_to "Inicio", root_path, class: 'btn btn-secondary' %></span>
        <span><%= link_to "Editar perfil", edit_user_path(@user), class: 'btn btn-dark '%></span>
        <% if current_user.present? &&  current_user.isAdmin? %>
          <% if @user.isAdmin %>
          <span><%= link_to "Ver Admins", admins_path, class: 'btn btn-warning' %></span>
          <% else %>
          <span><%= link_to "Ver Usuarios", users_path, class: 'btn btn-info' %></span>
          <% end %>
        <% end %>
      </div>

      <div class="col">
        <!--Revisa si un usuario es premium o no dependiendo de condiciones para mostrar el boton correspondiente-->
        <% if !current_user.isAdmin? %> <!--Pregnta si es un usuario comun-->
          <% if current_user.isPremium == "no" %> <!--Si lo es, pregunta si solicito ser premium-->
              <span><%= link_to "Pasar a ser premium", be_premium_user_path, class: 'btn btn-info' %></span>
          <% end %>
        <% else %> <!--Si no es asi, entonces es un administrador-->
          <% if @user.isPremium == "solicitado" %> <!--Revisa si el usuario que esta mirando el administrador solicito ser premium-->
            <span><%= link_to "Habilitar premium", enable_premium_user_path, class: 'btn btn-info' %></span>
          <% else %>
            <% if @user.isPremium == "si" %> <!--Si no entro en el anterior if, pregunta si ya es un usuario premium-->
              <span><%= link_to "Desabilitar premium", disable_premium_user_path, class: 'btn btn-danger' %></span>
            <% end %>
          <% end %>
        <% end %>
      </div>

      <div class="col">
        <!-- BORRAR USER -->
        <% if current_user.present? && !current_user.isAdmin? %>
            <% if not current_user.isPremium %>
              <span><%= link_to "Borrar mi cuenta premium", client_delete_path, class: 'btn btn-danger' %></span>
            <% else %>
              <span><%= link_to "Borrar mi cuenta", client_delete_path, class: 'btn btn-warning' %></span>
            <% end %>
          <% else if !@user.isAdmin? && current_user.isAdmin? %>
            <!-- <span><%= link_to "Borrar este usuario", client_delete_path, class: 'btn btn-danger' %></span> -->
          <% else if @user.isAdmin? && current_user.isAdmin? && current_user != @user %>
            <!-- <span><%= link_to "Borrar este admin", admin_destroy_path, class: 'btn btn-danger' %></span> -->
          <% end %>
          <% end %>
        <% end %>
      </div>

    </div>
  </div>
</div>