config/routes.rb
Rails.application.routes.draw do

  	devise_for :users
	root 'main#index' #redirecciona a la pagina principal
    get '/faq', to:'preguntasfrecuentes#faq' #ruta para poder acceder a las faq

    resources :residences, :auctions, :users, :searches, :hotsales, :reservations, :availabilitys, :settings #para poder acceder a las residencias, subastas, usuarios y busquedas
    resources :users do
  		member do
    		get 'be_premium'
            get 'apply_premium'
            get 'enable_premium'
            get 'disable_premium'
 		end
	end
    #ADMINISTRADORES
    get '/admins', to:'users#indexAdmins'
    get '/admins/new', to:'users#newAdmin'
    post '/admins', to:'users#createAdmin'
    get '/admins/:id/destroy', to:'users#destroyAdmin'
    delete '/admins/:id/destroy', to:'users#destroyAdmin', as: 'admin_destroy'

    #USERS
    get '/clients/:id/delete', to:'users#deleteClient', as: 'client_delete'
    get '/clients/deleted', to:'users#deletedClient', as: 'client_deleted'
    get '/clients/:id/destroy', to:'users#destroyClient'
    delete '/clients/:id/destroy', to:'users#destroyClient', as: 'client_destroy'

    #RESERVAS
    get '/reservations/:id/pay_reservation', to: 'reservations#pay_reservation', as: 'pay_reservation' 
    post '/reservations/:id/pay', to: 'reservations#pay', as: 'pay'

    #
    get '/enterBid', to:'auctions#enterBid'
    get '/contact', to:'contacto#contact'
    post '/contact_success', to:'contacto#contact_success'
end

app/models/residence.rb
class Residence < ApplicationRecord
	default_scope -> { order :name }
	has_many :auctions
	has_many :reservations
	has_many :availabilities, dependent: :destroy
	validates :image_url, allow_blank: true, format: { with: %r{.(gif|jpg|png)\Z}i, message: 'must be a URL for GIF, JPG or PNG image.' }
	
	scope :open, -> {where(available: 1)}
  	scope :closed, -> {where(available: 0)}

	def self.search(search)
		if search
			where(["name LIKE ? OR dir LIKE ? OR country LIKE ? OR province LIKE ? OR locality LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%"])
		else
			Residence.all
		end
	end
end

app/controllers/residences_controller.rb
class ResidencesController < ApplicationController
  
  def index
      @residence = Residence.search(params[:search])
  end

  def new
  	@residence = Residence.new #creo una nueva residencia
  end

  def create    #Crea una nueva residencia y la guarda en la base de datos
    @residence = Residence.new( params.require(:residence).permit(:name, :country, :province, :locality, :dir, :desc, :available, :image_url) )
    if @residence.save
      redirect_to residences_path  #redirecciono a la pagina de residencias
    else
      if (@residence.errors.added? :image_url)
        @error = "Error de validacion de URL. La imagen tiene que ser gif jpg png"
      end
      render :new
    end
    AvailabilityController.init(@residence.id)
  end

  def show
  	@residence = Residence.find(params[:id]) #Asigna la residencia a la variable residencia
    @auctionsOpen = @residence.auctions.open
    @auctionsClosed = @residence.auctions.closed
    @reservations = @residence.reservations
    @availabilities = @residence.availabilities
  end

  def edit
    @residence = Residence.find(params[:id])
  end

  def destroy            #elimina una residencia de la base de datos
    @residence = Residence.destroy(params[:id])
    redirect_to residences_path
  end

  def update
    @residence = Residence.find(params[:id])
    @residence.update(residence_params)
    redirect_to residences_path, notice: "Se actualizo la residencia con exito"
  end
  #Usado para mandar parametros de la residencia. Lo uso en la modificacion de residencia para actualizar los datos.
  #Se puede usar para otros metdos, como por ej. create.
  def residence_params
    params.require(:residence).permit(:name, :desc, :dir, :available, :image_url, :country, :province, :locality)
  end

#  def enterBids
#     auctions.each do |auction|
#      auction.enterBid
#    end
#  end

end

app/helpers/residences_helper.rb
module ResidencesHelper
end

app/views/residences/_formResidence.html.erb
<div class="container">

  <div class="form row">    <%= form_for @residence do |f| %>

   <div class="row">
      <div class="col">

        <div class="row">
          <%= f.label :name, 'Nombre de residencia' %>
          <%= f.text_field :name, required: true, placeholder: "Nombre", class: 'form-control' %>
        </div>

        <div class="row">
          <%= f.label :country, 'Pais' %>
          <%= f.text_field :country, required: true, placeholder: "Argentina", class: 'form-control' %>
        </div>

        <div class="row">
          <%= f.label :province, 'Provincia' %>
          <%= f.text_field :province, required: true, placeholder: "Buenos Aires", class: 'form-control' %>
        </div>

        <div class="row">
          <%= f.label :image_url, 'Ingrese la URL con la foto de la residencia:' %>
          <%= f.url_field :image_url, required: true, placeholder: "Ingrese una URL", class: 'form-control' %>
        </div>

      </div>

      <div class="col">

        <div class="row">
          <%= f.label :dir, 'Direccion' %>
          <%= f.text_field :dir, required: true, placeholder: "Calle 12 N°34", class: 'form-control' %>
        </div>

        <div class="row">
          <%= f.label :available, 'Disponibilidad' %>
          <%= f.select :available, [['Disponible', true], ['No disponible', false]], {}, {class: "form-control"} %>
        </div>

        <div class="row">
          <%= f.label :locality, 'Localidad' %>
          <%= f.text_field :locality, required: true, placeholder: "La Plata", class: 'form-control' %>
        </div>

        <div class="row">
          <%= f.label :desc, 'Descripcion' %>
          <%= f.text_area :desc, required: true, placeholder: "Descripcion de la residencia", class: 'form-control' %>
        </div>
      </div>
    </div>

    <div class="form-footer row">
      <div class="col-sm">
        <div class="row">
          <span class="error"> <%= @error %> </span>
        </div>
        <div class="row">
          <div class="btn-gap">
            <%= link_to "Volver", residences_path, class: 'btn btn-secondary' %>
            <%= f.submit 'Guardar', class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    </div>

  <% end %>

  </div>
</div>

app/views/residences/destroy.html.erb
<div class="hsh-window">
	<div class="container">
		<h1> Borrar Residencia </h1>

	  <%= form_for(:residence, :url => {:action => 'destroy', :id => @residence.id}) do |f| %>
	    <p>Borrar esta residencia - Ok?</p>
	    <%= submit_tag("Borrar") %>
	  <% end %>
	</div>
</div>

app/views/residences/edit.html.erb
<div class="hsh-window">
    <h1> Modificar la residencia "<%= @residence.name %>" </h1>
    <%= render 'formResidence' %>
</div>

app/views/residences/index.html.erb
<div class="hsh-window">
	<div class="container">

		<div class="row">
			<div class="col">

			    <!-- Buscador -->
				<div class="container">
					<div class="row justify-content-center">
						<div class="col-12 col-md-10 col-lg-8">
							<form class="card card-sm">
								<div class="card-body row no-gutters align-items-center">
								    <%= form_tag residences_path, :method => 'get' do%>
								    	<div class="col">
								    		<%= text_field_tag :search, params[:search], placeholder:"Ingrese Nombre, Direccion, Pais, Provincia o Localidad", class:"form-control form-control-lg form-control-borderless " %>
								    	</div>
								    	<div class="col-auto">
								    		<%= submit_tag "Buscar", class:"btn btn-lg btn-success"%>
								    	</div>
								    <% end %>
								</div>
							</form>
							<%= link_to "Busqueda Avanzada", new_search_path %>
						</div>
					</div>
				</div>
				<br/>


				<h1> Listado de Residencias </h1>  <!-- TABLA DE RESIDENCIAS-->
				<% if current_user.present? && current_user.isAdmin?%>
					<p class="br30"><%= link_to "Crear Residencia", new_residence_path ,class: 'btn btn-info'%></p>
				<%end%>
			</div>
		</div>
		<!-- RESIDENCIAS ACTIVAS -->
		<div class="row br30">
			<table class="table">

				<tr>
					<th>  </th>
					<th> Nombre </th>
					<th> Descripción </th>
					<th> Direccion </th>
					<th> Localidad </th>
					<th>  </th>
					<th>  </th>
				</tr>

				
					<% @residence.each do |residence| %>
						<% if residence.available? %> <!-- Solo muestro las residencias disponibles-->
							<tr>
							<td><%= image_tag residence.image_url, height: '100', width: '200' %></td>
							<td> <%= link_to residence.name, residence, class: 'btn btn-link btn-sm'%> </td>
							<td> <%= truncate(residence.desc, length: 15, seperator: ' ') %> </td>
							<td> <%= residence.dir %> </td>
							<td> <%= "#{residence.country}, #{residence.province}, #{residence.locality}" %> </td>

 							<!-- Funciones exclusivas para administradores -->
							<% if user_signed_in? && current_user.isAdmin? %>
								<td><%= link_to "Editar", edit_residence_path(residence), class: 'btn btn-dark btn-sm'%></td>
								<!-- Se fija si en el listado hay residencias que se encuentran en subasta -->
								<% if Auction.exists?(residence_id: residence.id) %>
									<td><%= link_to "En subasta", residence, method: :delete,  class: 'btn btn-danger btn-sm disabled', data: { confirm: 'Realmente desea borrar la residencia?'}%></td>
								<% else %>
									<td><%= link_to "Borrar", residence, method: :delete,  class: 'btn btn-danger btn-sm', data: { confirm: 'Realmente desea borrar la residencia?'}%></td>
								<% end %>
							<% end %>
							</tr>
					<% end %>
				<% end %>

				<% if @residence.size == 0 %>
					<tr> <td colspan="3"> No hay residencias </td> </tr>
				<% end %>

			</table>
		</div>
		<!-- RESIDENCIAS NO DISPONIBLES -->
		<% if user_signed_in? %>
		<% if current_user.isAdmin? %>
		<div class="row br30">
			<h1> Listado de Residencias No Disponibles </h1>  <!-- TABLA DE RESIDENCIAS-->
			<table class="table">

				<tr>
					<th>  </th>
					<th> Nombre </th>
					<th> Descripción </th>
					<th> Direccion </th>
					<th> Localidad </th>
					<th>  </th>
					<th>  </th>
				</tr>


				
					<% @residence.each do |residence| %>
						<% if !residence.available? %> <!-- Solo muestro las residencias disponibles-->
							<tr>
							<td><%= image_tag residence.image_url, height: '100', width: '200' %></td>
							<td> <%= link_to residence.name, residence, class: 'btn btn-link btn-sm'%> </td>
							<td> <%= truncate(residence.desc, length: 15, seperator: ' ') %> </td>
							<td> <%= residence.dir %> </td>
							<td> <%= "#{residence.country}, #{residence.province}, #{residence.locality}" %> </td>

 							<!-- Funciones exclusivas para administradores -->
							<% if user_signed_in? && current_user.isAdmin? %>
								<td><%= link_to "Editar", edit_residence_path(residence), class: 'btn btn-dark btn-sm'%></td>
								<!-- Se fija si en el listado hay residencias que se encuentran en subasta -->
								<% if Auction.exists?(residence_id: residence.id) %>
									<td><%= link_to "En subasta", residence, method: :delete,  class: 'btn btn-danger btn-sm disabled', data: { confirm: 'Realmente desea borrar la residencia?'}%></td>
								<% else %>
									<td><%= link_to "Borrar", residence, method: :delete,  class: 'btn btn-danger btn-sm', data: { confirm: 'Realmente desea borrar la residencia?'}%></td>
								<% end %>
							<% end %>
							</tr>
					<% end %>
				<% end %>

				<% if @residence.size == 0 %>
					<tr> <td colspan="3"> No hay residencias </td> </tr>
				<% end %>

			</table>
		</div>
		<% end %>
		<% end %>

		<div class="row">
			<p class="br30"> <%= link_to "Volver a pagina de inicio", root_path, class: 'btn btn-secondary' %> </p>
		</div>

	</div>
</div>

app/views/residences/new.html.erb
<div class="hsh-window">
	<h1> Alta de residencia </h1>
	<%= render 'formResidence' %>
</div>

app/views/residences/show.html.erb
<div class="hsh-window">
  <div class="container">

    <!-- IMAGENES DE RESIDENCIA -->
    <div class="row residence-images">
      <div class="container">

        <div class="row br10">
          <div class="col">
            <% if @residence.image_url?  %> <!--&& Utils.image_exists?(@residence.image_url) -->    <!--Revisa si la residencia tiene una foto. Si no, mostrara una imagen de no disponible-->
              <%= image_tag @residence.image_url , class: 'img-fluid residence-pic fit' %>
            <% else %>
              <%= image_tag 'no_disponible.jpg', class: 'img-fluid' %>
            <% end %>
          </div>
          <div class="col">
            <% if @residence.image_url?  %> <!--&& Utils.image_exists?(@residence.image_url) -->
              <%= image_tag @residence.image_url , class: 'img-fluid residence-pic fit' %>
            <% else %>
              <%= image_tag 'no_disponible.jpg', class: 'img-fluid' %>
            <% end %>
          </div>
          <div class="col">
            <% if @residence.image_url?  %> <!--&& Utils.image_exists?(@residence.image_url) -->
              <%= image_tag @residence.image_url , class: 'img-fluid residence-pic fit' %>
            <% else %>
              <%= image_tag 'no_disponible.jpg', class: 'img-fluid' %>
            <% end %>
          </div>
        </div>

        <div class="row">
          <div class="col">
            <% if @residence.image_url?  %> <!--&& Utils.image_exists?(@residence.image_url) -->
              <%= image_tag @residence.image_url , class: 'img-fluid residence-pic fit' %>
            <% else %>
              <%= image_tag 'no_disponible.jpg', class: 'img-fluid' %>
            <% end %>
          </div>
          <div class="col">
            <% if @residence.image_url?  %> <!--&& Utils.image_exists?(@residence.image_url) -->
              <%= image_tag @residence.image_url , class: 'img-fluid residence-pic fit' %>
            <% else %>
              <%= image_tag 'no_disponible.jpg', class: 'img-fluid' %>
            <% end %>
          </div>
          <div class="col">
            <% if @residence.image_url?  %> <!--&& Utils.image_exists?(@residence.image_url) -->
              <%= image_tag @residence.image_url , class: 'img-fluid residence-pic fit' %>
            <% else %>
              <%= image_tag 'no_disponible.jpg', class: 'img-fluid' %>
            <% end %>
          </div>
        </div>

      </div>
    </div>

    <!-- INFORMACION DE RESIDENCIA -->
    <div class="row residence-content">
      <div class="container">
        <!-- DESCRIPCION -->
        <div class="row br30">
          <div class="col">
            <h1><%= @residence.name %></h1> <!--DESCRIPCION DE UNA RESIDENCIA-->
            <h6><%= image_tag 'ubication.png', height: '30', width: '20' %> <%= @residence.dir %>, <%= @residence.locality %>, <%= @residence.province %>, <%= @residence.country %></h6>
            <h5>Descripcion</h5>
            <p><%= @residence.desc %></p>
          </div>
        </div>
        <!-- SUBASTAS -->
        <div class="row br30">
          <h2>Subastas Activas de esta residencia:</h2>
          <table class="table">
            <tr>
              <th> Precio Actual</th>
            </tr>
          	<% @auctionsOpen.each do |auction| %>
            <tr>
              <td> <%= auction.maxbid %> </td>
              <td> <%= link_to "Ir a subasta", auction, class: 'btn btn-secondary' %> </td>
            </tr>
            <% end %>
          </table>
        </div>
        <!-- SUBASTAS PENDIENTES-->
        <% if user_signed_in? %>
        <% if current_user.isAdmin? %>
        <div class="row br30">
          <h2>Subastas Pendientes de esta residencia:</h2>
          <table class="table">
            <tr>
              <th> Precio Actual</th>
            </tr>
          	<% @auctionsClosed.each do |auction| %>
            <tr>
              <td> <%= auction.maxbid %> </td>
              <td> <%= link_to "Ir a subasta", auction, class: 'btn btn-secondary' %> </td>
            </tr>
            <% end %>
          </table>
        </div>
        <% end %>
        <% end %>
        <!-- RESIDENCIA EN SEMANA -->
        <div class="row">
          <!--
          <h2>Residencia en semana</h2>
          <table class="table">
            <tr>
              <th>Año</th>
              <th>Semana</th>
              <th>Ganador</th>
            </tr>
          	<% @reservations.each do |reservation| %>
            <tr>
              <td> <%= reservation.year %> </td>
              <td> <%= reservation.week %> </td>
              <td> <%= reservation.user.userName %> </td>
            </tr>
            <% end %>
          </table> -->
        </div>
        <!-- DISPONIBILIDAD -->
        <div class="row br30">
          <h2>Disponibilidad de residencia en semanas</h2>
          <table class="table">
              <tr>
                <th>Desde</th>
                <th>Hasta</th>
              </tr>
              <% for i in 24 .. 31 do %> <!--NOTA IMPORTANTE: "24" indica el valor de id en la tabla que serian 6 meses despues de la semana de la fecha actual, mientras que "31" serian dos meses despues de estos seis meses. Esto me muestra una franja acotada.  -->
                <% if @availabilities[i].is_available %>
                  <tr>
                    <td>  <%= Date.commercial(@availabilities[i].year, @availabilities[i].week).strftime("%d/%m/%Y") %>  </td>
                    <td>  <%= (Date.commercial(@availabilities[i].year, @availabilities[i].week)+6).strftime("%d/%m/%Y") %>  </td> <!-- Esto muestra el ultimo dia de la semana que corresponde -->
                    <% if current_user.present? && current_user.isAdmin? && !Auction.exists?(:availability_id => @availabilities[i])%>
                      <td><%= link_to "Crear Subasta", new_auction_path(:id => @residence.id, :aid => @availabilities[i]) ,class: 'btn btn-info'%></td>
                    <%end%>
                    <% if current_user.present? && current_user.isPremium == 'si' && !Auction.exists?(:availability_id => @availabilities[i])%>
                      <% if current_user.credits > 0 %>
                        <td><%= link_to "Compra Directa", new_reservation_path(:id => @residence.id, :aid => @availabilities[i]) ,class: 'btn btn-warning'%></td>
                      <% else %>
                        <td><%= link_to "No tiene creditos", new_reservation_path(:id => @residence.id, :aid => @availabilities[i]) ,class: 'btn btn-warning disabled'%></td>
                      <% end %>
                    <%end%>
                  </tr>
                <% end %>
              <% end %>
            </table>
        </div>
        <!-- MENU -->
        <div class="row">
          <p class="br30"><%= link_to "Volver al listado de residencias", residences_path, class: 'btn btn-primary' %></p>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/residences/update.html.erb
<div class="hsh-window">
  <div class="container">
    <h1> Cambios guardados </h1>
    <h2><%= @residence.name %></h2>
  </div>
</div>