config/routes.rb
Rails.application.routes.draw do

  	devise_for :users
	root 'main#index' #redirecciona a la pagina principal
    get '/faq', to:'preguntasfrecuentes#faq' #ruta para poder acceder a las faq

    resources :residences, :auctions, :users, :searches, :hotsales, :reservations, :availabilitys, :settings #para poder acceder a las residencias, subastas, usuarios y busquedas
    resources :users do
  		member do
    		get 'be_premium'
            get 'apply_premium'
            get 'enable_premium'
            get 'disable_premium'
 		end
	end
    #ADMINISTRADORES
    get '/admins', to:'users#indexAdmins'
    get '/admins/new', to:'users#newAdmin'
    post '/admins', to:'users#createAdmin'
    get '/admins/:id/destroy', to:'users#destroyAdmin'
    delete '/admins/:id/destroy', to:'users#destroyAdmin', as: 'admin_destroy'

    #USERS
    get '/clients/:id/delete', to:'users#deleteClient', as: 'client_delete'
    get '/clients/deleted', to:'users#deletedClient', as: 'client_deleted'
    get '/clients/:id/destroy', to:'users#destroyClient'
    delete '/clients/:id/destroy', to:'users#destroyClient', as: 'client_destroy'

    #RESERVAS
    get '/reservations/:id/pay_reservation', to: 'reservations#pay_reservation', as: 'pay_reservation' 
    post '/reservations/:id/pay', to: 'reservations#pay', as: 'pay'

    #
    get '/enterBid', to:'auctions#enterBid'
    get '/contact', to:'contacto#contact'
    post '/contact_success', to:'contacto#contact_success'
end

app/models/auction.rb
class Auction < ApplicationRecord
	belongs_to :residence
	has_and_belongs_to_many :users
	belongs_to :user
	belongs_to :availability

 	#FUNCTION SQL PARA ENCONTRAR UNA FECHA ENTRE DOS FECHAS
	#scope :open, -> { where("? BETWEEN dateStart AND dateEnd", Date.today)}
	#scope :closed, -> { where("? NOT BETWEEN dateStart AND dateEnd", Date.today)}

	#FUNCTION POSTGRESQL PARA ENCONTRAR UNA FECHA ENTRE DOS FECHAS
 	scope :open, -> {where(':date BETWEEN Auctions."dateStart" AND Auctions."dateEnd"', date: Date.today)}
 	scope :closed, -> {where(':date NOT BETWEEN Auctions."dateStart" AND Auctions."dateEnd"', date: Date.today)}
	scope :pending, -> {where(':date < Auctions."dateStart"', date: Date.today)}
 	scope :finished, -> {where(':date > Auctions."dateEnd"', date: Date.today)}

	def isActive()
		if Date.today > self.dateStart && Date.today < self.dateEnd
			return true
		else
			return false
		end
	end

end

app/models/auctions_user.rb
class AuctionsUser < ApplicationRecord
  belongs_to :user
  belongs_to :auction
end

app/models/availability.rb
class Availability < ApplicationRecord
  belongs_to :residence
end

app/models/hotsale.rb
class Hotsale < ApplicationRecord
  belongs_to :residence
  belongs_to :availability
  
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :residence
  belongs_to :user
end

app/models/residence.rb
class Residence < ApplicationRecord
	default_scope -> { order :name }
	has_many :auctions
	has_many :reservations
	has_many :availabilities, dependent: :destroy
	validates :image_url, allow_blank: true, format: { with: %r{.(gif|jpg|png)\Z}i, message: 'must be a URL for GIF, JPG or PNG image.' }
	
	scope :open, -> {where(available: 1)}
  	scope :closed, -> {where(available: 0)}

	def self.search(search)
		if search
			where(["name LIKE ? OR dir LIKE ? OR country LIKE ? OR province LIKE ? OR locality LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%"])
		else
			Residence.all
		end
	end
end

app/models/search.rb
class Search < ApplicationRecord

	def search_residences
		residences = Residence.all

		residences = residences.where(["name LIKE ?","%#{keywords}%"]) if keywords.present?
		residences = residences.where(["dir LIKE ?","%#{dir}%"]) if dir.present?
		#residences = residences.where(["desc LIKE ?","%#{desc}%"]) if desc.present?
		residences = residences.where(["country LIKE ?","%#{country}%"]) if country.present?
		residences = residences.where(["province LIKE ?","%#{province}%"]) if province.present?
		residences = residences.where(["locality LIKE ?","%#{locality}%"]) if locality.present?

		return residences
	end
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_and_belongs_to_many :auctions
  has_many :reservations

  enum isPremium: { si: 0, solicitado: 1, no: 2 }

  scope :admins, -> {where(isAdmin: 1)}
  scope :clients, -> {where(isAdmin: 0)}

  validate :age_is_invalid, :expiry_date_is_invalid, :credit_card_number_is_invalid

  #Deje el self.isAdmin porque current_user solo funciona cuando lo usas desde un controlador o una vista. NO funciona en modelos, para eso hay que usar el self.
  def age_is_invalid
    if self.isAdmin == false
      today = Date.today
      if today - self.birthday < 18
        errors.add(:birthday, "Necesita ser mayor de edad para registrarse")
      end
    end
  end

  def expiry_date_is_invalid
    if self.isAdmin == false
  	 if self.card_expiry_date.present? && card_expiry_date <= Date.today
      	 errors.add(:card_expiry_date, "La fecha de vencimiento de la tarjeta ha caducado o esta punto de vencer")
      end
    end
  end

  def credit_card_number_is_invalid
    if self.isAdmin == false
     if self.credit_card_number.present? && self.credit_card_number.to_s.length < 14
         errors.add(:credit_card_number, "El numero de la tarjeta debe ser de al menos 14 digitos")
      end
    end
  end

  def cvv_is_invalid
    if self.isAdmin == false
      if self.cvv? && self.cvv.to_s.length < 3
        errors.add(:cvv, "El numero de la clave de seguridad de la tarjeta debe ser de al menos 3 digitos")
      end
    end
  end

end

app/models/utils.rb
class Utils
  require 'net/http'
  require 'uri'

  def self.image_exists?(url_param)
    url = URI.parse(url_param)
    http = Net::HTTP.start(url.host, url.port)
    binding.pry
    http.head(url.request_uri)['Content-Type'].start_with? 'image'
  end

end

app/helpers/auction_helper.rb
module AuctionHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/helpers/contacto_helper.rb
module ContactoHelper
end

app/helpers/hotsales_helper.rb
module HotsalesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>  <!-- Footer -->
	<nav class="navbar navbar-expand-lg navbar-dark">
			<div class="container footerlist col-8">
				<ul>
					<li><%= link_to "Pagina principal", root_path%></li>
					<li><%= link_to 'Ver Preguntas Frecuentes', faq_path%></li>
					<li><%= link_to "Contacto", contact_path%></li>
				</ul>
			</div>
			<div class="col"></div>
			<div class="col"><%= image_tag "logo.png", title: "Logo", id:"logo"%></div>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <!-- Navigation -->
  <nav id="hsh-header" class="row navbar navbar-expand-lg navbar-dark fixed-top">
    <div class="container">

      <%= link_to root_path, class: 'navbar-brand' do %>    <!-- Link a pagina principal (tocando logo o titulo)-->
      <h2 class="header-logo">  <!-- titulo color blanco y logo-->
      <%= image_tag "HSH-Logo.png", title: "Logo", class: "logo" %>
      <%= image_tag "HSH-Text.png", title: "Logo", class: "logo" %>
      </h2>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">

          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to "Residencias", residences_path, class: 'nav-link'%>
            </li>
            <li class="nav-item">
              <%= link_to "Subastas", auctions_path, class: 'nav-link'%>
            </li>
            <% if current_user.present? && current_user.isAdmin?%>
            <li class="nav-item">
              <%= link_to "Usuarios", users_path, class: 'nav-link'%>
            </li>
            <li class="nav-item">
              <%= link_to "Admins", admins_path, class: 'nav-link'%>
            </li>
            <li class="nav-item">
              <%= link_to "Cuotas", setting_path(:id => 1), class: 'nav-link'%>
            </li>
          <% end %>
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to current_user.userName, current_user, class: 'nav-link'%></li>
            <li class="nav-item">
              <%= link_to 'Cerrar Sesion', destroy_user_session_path, method: :delete, class: 'nav-link'%></li>
          <% else%>
            <li class="nav-item">
              <%= link_to "Iniciar Sesion", new_user_session_path, class: 'nav-link'%></li>
            <li class="nav-item">
              <%= link_to "Registrarse", new_user_registration_path, class: 'nav-link'%></li>
          <% end %>
          </ul>

        </div>
    </div>
  </nav>

  <div id="notice" class="row fixed-top noselect">
    <% if flash[:notice] %>
    <div id="notice-content" class="container alert alert-info">
          <%# <% flash.each do |key, notice| %>
      <%= notice %>
    <% end %>
    </div>
  </div>

  <div id="deviseERR" class="row noselect">
    <div id="deviseERR-content" class="container danger alert-danger">
      <%= devise_error_messages! %>
    </div>
  </div>


</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

		<!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/full.css" rel="stylesheet">

	  <title>Home Switch Home</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	  <%= csrf_meta_tags %>
	</head>

	<body>
		<div>
		<%= render 'layouts/header' %>
		</div>
		<div class="hsh-content">
			<%= yield %>
		</div>
		<div>
		<%= render 'layouts/footer' %>
		</div>

	</body>

	<!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

	<!-- Notice timeout -->

	<script type="text/javascript">
$(document).ready(function(){
  setTimeout(function(){
    $('#notice').remove();
  }, 5000);
 })
</script>

</html>